# Generated by Django 3.0.5 on 2020-04-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='educaation',
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.TextField(default=None, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='application',
            name='written_cover_letter',
            field=models.TextField(verbose_name='Сопроводительное письмо'),
        ),
        migrations.AlterField(
            model_name='application',
            name='written_phone',
            field=models.CharField(max_length=64, verbose_name='Телефон автора'),
        ),
        migrations.AlterField(
            model_name='application',
            name='written_username',
            field=models.CharField(max_length=64, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(max_length=64, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(max_length=64, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(default=None, null=True, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='grade',
            field=models.CharField(choices=[('tr', 'Стажёр'), ('jn', 'Джуниор'), ('md', 'Мидл'), ('sn', 'Синьор'), ('ld', 'Лид')], default='tr', max_length=2, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='portfolio',
            field=models.FileField(upload_to='user_directory_path', verbose_name='Портфолио'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.PositiveIntegerField(verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='specialty',
            field=models.CharField(max_length=64, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('DFJ', 'Не ищу работу'), ('LO', 'Рассматриваю предложения'), ('LFJ', 'Ищу работу')], default='LFJ', max_length=3, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='surname',
            field=models.CharField(max_length=64, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.CharField(max_length=64, verbose_name='Пользователь'),
        ),
    ]
