# Generated by Django 3.0.5 on 2020-04-23 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20200423_2312'),
        ('account', '0002_auto_20200423_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='jobs.Vacancy'),
        ),
    ]
