# Generated by Django 3.0.5 on 2020-04-19 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0011_vacancy_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('DFJ', 'Не ищу работу'), ('LO', 'Рассматриваю предложения'), ('LFJ', 'Ищу работу')], default='LFJ', max_length=3)),
                ('salary', models.PositiveIntegerField()),
                ('specialty', models.CharField(max_length=64)),
                ('grade', models.CharField(choices=[('tr', 'Стажёр'), ('jn', 'Джуниор'), ('md', 'Мидл'), ('sn', 'Синьор'), ('ld', 'Лид')], default='tr', max_length=2)),
                ('educaation', models.TextField()),
                ('experience', models.TextField()),
                ('portfolio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('company', models.CharField(max_length=64)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myuser', to='users.Resume')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_username', models.CharField(max_length=64)),
                ('written_phone', models.CharField(max_length=64)),
                ('written_cover_letter', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='jobs.Vacancy')),
            ],
        ),
    ]
