# Generated by Django 3.0.5 on 2020-04-18 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_vacancy_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='job_vacancies', to='jobs.Company'),
            preserve_default=False,
        ),
    ]
