# Generated by Django 3.0.5 on 2020-04-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_vacancy_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.CharField(max_length=64),
        ),
    ]
