# Generated by Django 3.0.5 on 2020-04-19 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
        ('jobs', '0011_vacancy_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='applications',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='account.Application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
