# Generated by Django 3.0.5 on 2020-04-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20200419_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='height_field',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='width_field',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(height_field='height_field', upload_to='company_logo', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(upload_to='specialty_pictures'),
        ),
    ]
